services:
    api:
        build:
            context: ./api
        platform: linux/amd64
        ports:
            - 3000:3000
        command:
            - /bin/bash
            - -c
            - |
                exec uvicorn app.main:app --host 0.0.0.0 --port 3000 --reload --reload-dir /api
        volumes:
            - ./api:/api
        working_dir: /api
        depends_on:
            postgis:
                condition: service_healthy
    ui:
        image: node:20-bullseye-slim
        ports:
            - 5173:5173
        volumes:
            - ./ui/:/app
        working_dir: /app
        command:
            - /bin/bash
            - -c
            - |
                npm install
                npm run dev -- --host
    postgis:
        image: kartoza/postgis:16-3.4
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASS=postgres
            - POSTGRES_DB=postgres
        ports:
            - '5432:5432'
        volumes:
            - postgis-data:/var/lib/postgresql
            - ./postgis-init/:/docker-entrypoint-initdb.d/
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready']
            interval: 10s
            timeout: 10s
            retries: 10

volumes:
    postgis-data:
